sudo: false
language: go
go:
  - 1.9
  - 1.8
  - master

before_install:
  - go get -t -v ./...

script:
  - go install ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
