sudo: false
language: go
go:
  - 1.9
  - 1.8
  - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
  - go get -t -v ./...

install:
  - go install ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
